config/routes.rb
Rails.application.routes.draw do
  
  
 
  resources :users, only: [:new, :create, :show] do 
    resources :translations, :orders, :restaurants, :comments, only: [:index]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#facebook'
  delete '/sessions', to: 'sessions#destroy'

  resources :restaurants do 
    resources :translations, only: [:new, :create, :index]
    resources :orders, only: [:new, :create, :index]
    resources :dishes, only: [:index]
  end

  resources :translations, only: [:show, :edit, :update, :destroy] do 
    resources :dishes, only: [:new, :create]
    resources :comments, only: [:new, :create, :index]
  end

  resources :orders, only: [:show, :edit, :update, :destroy]
  resources :dishes, only: [:show, :edit, :update, :destroy] do 
    resources :dish_orders, only: [:create]
  end
  resources :dish_orders, only: [:destroy]
  resources :comments, only: [:show, :edit, :update, :destroy]
   
  
  root 'application#home'

  get '/read', to: 'polly#read'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/translation.rb
class Translation < ApplicationRecord
    belongs_to :restaurant 
    has_many :dishes 
    belongs_to :language 
    belongs_to :user 
    has_many :comments 
    validates :title, presence: true 
    has_one_attached :menu 

    def average_rating 
        if self.comments.size > 0
            self.comments.map { |c| c.rating }.sum/self.comments.size
        else 
            0
        end 
    end

    

    
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
    before_action :set_restaurant, only: [:new, :create]
    before_action :set_translation, only: [:show, :edit, :update, :destroy]
    skip_before_action :check_if_logged_in, only: [:show]
    before_action :user_has_permission?, only: [:edit, :update, :destroy]
    
    
    def new 
        @translation = @restaurant.translations.build 
    end

    def create 
        @translation = @restaurant.translations.build(translation_params)
        @translation.user = current_user 
        # create a Restaurant instance method :build_translation_with_user(params, user) ???
        if @translation.save 
            redirect_to translation_path(@translation), notice: "Translation was successfully created."
        else 
            render :new 
        end
    end

    def show 
        @dish = Dish.new
    end

    def index 
        if params[:restaurant_id]
            set_restaurant
            set_restaurant_translations
        else 
            @user= User.find(params[:user_id])
            @translations = @user.translations
        end
    end

    def edit 

    end

    def update 
        if @translation.update(translation_params)
            redirect_to translation_path(@translation), notice: "Translation was succesfully updated."
        else 
            render :edit 
        end
    end

    def destroy 
        @restaurant = @translation.restaurant 
        @translation.destroy
        redirect_to restaurant_path(@restaurant), notice: "Translation was successfully destroyed."
    end

    private 

    def set_restaurant 
        @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def translation_params 
        params.require(:translation).permit(:title, :notes, :menu, :language_id)
    end

    def set_translation
        @translation = Translation.find(params[:id])
    end

    def set_restaurant_translations
        if params[:order_by] == "average_rating"
            @translations = @restaurant.sort_translations_by_rating
        elsif params[:order_by] == "number_of_dishes"
            @translations = @restaurant.sort_translations_by_dishes_count
        elsif params[:order_by] == "created_at"
            @translations = @restaurant.translations.sort_by_created_at
        else 
            @translations = @restaurant.translations
        end
    end

    def user_has_permission? 
        unless current_user == @translation.user 
            redirect_to translation_path(@translation), alert: "You do not have permission to perform this action."
        end
    end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_form.html.erb
<%= form_with(model: [@restaurant, @translation] , local: true) do |f| %>

    <% if @translation.errors.any? %>
        <div id="error_explanation">
            <ul>
                <% @translation.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>

    <% end %>
    <%= f.label :language_id %>
    <%= f.collection_select(:language_id, Language.all, :id, :name) %> <br>
    <%= f.label :title %>
    <%= f.text_field :title %> <br>
    <%= f.label :notes %>
    <%= f.text_field :notes %> <br>
    <%= f.label :menu, "Add a picture of the menu" %> <br>
    <%= f.file_field :menu %> <br>
    <%= f.submit class: "border-button" %>
<% end %>

app/views/translations/_index.html.erb
<h1>Menu Translations: </h1>
<div class="translations-list">
    <% translations.each do |t| %>
        <div class="translation-item">
            <div class="translation-info">
                
                    <%= link_to t.title, translation_path(t) %>
                
                    by <%= link_to t.user.name, user_path(t.user) %>
                
                <p><%= t.created_at.strftime("%m/%d/%Y") %></p>
                <p> <%= t.notes %> </p>
                <p> <%= t.dishes.count %> dishes </p>
                <p> <%= t.comments.count %> comments, <%= t.average_rating %>/5 rating</p>
            </div>
            <%= render  partial: "dishes/preview_index", locals: {dishes: t.dishes.first(3)} %>
            
        </div>
    <% end %>
</div>

app/views/translations/_search.html.erb
<h3>Sort Translations By:</h3>
<%= form_with(url: restaurant_translations_path(@restaurant), method: "get", local: true) do %>
    
    <%= select_tag(:order_by, options_for_select([["Rating", "average_rating"], ["Number of Dishes", "number_of_dishes"], ["Date Posted", "created_at"]])) %>
    
    <%= submit_tag "Sort" %>
<% end %>

app/views/translations/edit.html.erb
<h1>Edit translation for: <%= @translation.restaurant.chinese_name %> </h1>


<%= render  "form" %>

app/views/translations/index.html.erb
<%= render  "restaurants/show" if @restaurant %>
<%= render  "users/show" if @user %>

<%= render  "search" if @restaurant %>

<%= render  partial: "index", locals: {translations: @translations} %>

app/views/translations/new.html.erb
<h1>New translation for: <span lang="zh"><%= @restaurant.chinese_name %></span> <%= link_to non_chinese_names(@restaurant), restaurant_path(@restaurant) %> </h1>

<%= render  "form" %>

app/views/translations/show.html.erb
<div class="top-content">
    <div >
        <%= cl_image_tag @translation.menu.key, width: 450, sign_url: true if @translation.menu.attached? %>
    </div>

    <div class="description">
        <h1><%= @translation.title %></h1>
        <h3>for: <span lang="zh"> <%= @translation.restaurant.chinese_name%> </span> 
            <%= link_to non_chinese_names(@translation.restaurant), restaurant_path(@translation.restaurant) %> 
            by: <%= link_to  @translation.user.name, user_path(@translation.user) %>
        </h3>
        <p><%= @translation.notes %> </p>
        <% if user_has_permission?(@translation) %>
            <nav id="translation">
                <%= link_to  "Edit", edit_translation_path(@translation) %>
                <%= link_to  "Delete", translation_path(@translation), method: "delete" %>
                <%= link_to  "Add Dish", new_translation_dish_path(@translation) %>
            </nav>
            <br>
            <br>
        <% end %>
    </div>
</div>




<div class="dish-list">
    <h1>Dishes</h1>
    <%= render  partial: "dishes/index", locals: {dishes: @translation.dishes } %>
</div>


<div class="comment-list">
    <h1>Comments:</h1>
    <%= render  partial: "comments/index", locals: {comments: @translation.comments } %>
    <%= link_to "Make a Comment", new_translation_comment_path(@translation) %>
</div>