config/routes.rb
Rails.application.routes.draw do
  
  
 
  resources :users, only: [:new, :create, :show] do 
    resources :translations, :orders, :restaurants, :comments, only: [:index]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#facebook'
  delete '/sessions', to: 'sessions#destroy'

  resources :restaurants do 
    resources :translations, only: [:new, :create, :index]
    resources :orders, only: [:new, :create, :index]
    resources :dishes, only: [:index]
  end

  resources :translations, only: [:show, :edit, :update, :destroy] do 
    resources :dishes, only: [:new, :create]
    resources :comments, only: [:new, :create, :index]
  end

  resources :orders, only: [:show, :edit, :update, :destroy]
  resources :dishes, only: [:show, :edit, :update, :destroy] do 
    resources :dish_orders, only: [:create]
  end
  resources :dish_orders, only: [:destroy]
  resources :comments, only: [:show, :edit, :update, :destroy]
   
  
  root 'application#home'

  get '/read', to: 'polly#read'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :translations 
    has_many :restaurants 
    has_many :orders 
    has_many :comments 
    has_secure_password 
    validates :name, presence: true 
    validates :name, uniqueness: true 
    validates :email, presence: true 
    validates :email, uniqueness: true 
    
    def top_rated_translations(n) 
        self.translations.sort_by { |t| t.average_rating }.reverse.first(n)
    end

    def most_recent_orders(n)
        Order.where("user_id = ?", self.id).order(created_at: :desc).first(n)
    end
    
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :check_if_logged_in, only: [:new, :create]

    def new 
        @user = User.new 
    end

    def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else 
            render :new
        end
    end

    def show 
        @user = User.find(params[:id])
    end

    private 

    def user_params 
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper

    def current_user
        User.find(session[:user_id])
    end

    def logged_in? 
        !!session[:user_id]
    end

    def user_has_permission?(o)
        logged_in? && current_user == o.user
    end 
end

app/views/users/_show.html.erb
<% if @user == current_user %>

    <h1>Welcome <%= @user.name %> </h1>

<% else%>

<h1>Profile for <%= @user.name %> </h1>
<% end %>
<nav class="user-show">
<%= link_to  "Translations", user_translations_path(@user) %>
<%= link_to  "Orders", user_orders_path(@user) %>
<%= link_to  "Restaurants", user_restaurants_path(@user) if @user == current_user %>
<%= link_to  "Comments", user_comments_path(@user) if @user == current_user %>
</nav>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_with( model: @user , local: true) do |f| %>

<% if @user.errors.any? %>
    <div id="error_explanation">
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>

<% end %>

<%= f.label :name %>
<%= f.text_field :name %> <br>
<%= f.label :email %>
<%= f.text_field :email %> <br>
<%= f.label :password %>
<%= f.password_field :password %> <br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %> <br>
<%= f.submit class: "border-button" %>
<% end %>

app/views/users/show.html.erb
<%= render  "show" %>

<%= render partial: "translations/index", locals: {translations: @user.top_rated_translations(3)} %>

<%= render partial: "orders/index", locals: {orders: @user.most_recent_orders(3)} %>