config/routes.rb
Rails.application.routes.draw do
  
  
 
  resources :users, only: [:new, :create, :show] do 
    resources :translations, :orders, :restaurants, :comments, only: [:index]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#facebook'
  delete '/sessions', to: 'sessions#destroy'

  resources :restaurants do 
    resources :translations, only: [:new, :create, :index]
    resources :orders, only: [:new, :create, :index]
    resources :dishes, only: [:index]
  end

  resources :translations, only: [:show, :edit, :update, :destroy] do 
    resources :dishes, only: [:new, :create]
    resources :comments, only: [:new, :create, :index]
  end

  resources :orders, only: [:show, :edit, :update, :destroy]
  resources :dishes, only: [:show, :edit, :update, :destroy] do 
    resources :dish_orders, only: [:create]
  end
  resources :dish_orders, only: [:destroy]
  resources :comments, only: [:show, :edit, :update, :destroy]
   
  
  root 'application#home'

  get '/read', to: 'polly#read'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user 
    belongs_to :restaurant 
    has_many :dish_orders 
    has_many :dishes, through: :dish_orders
    validates :name, presence: true  
    accepts_nested_attributes_for :dish_orders

    scope :sort_by_people, -> {order(:people)}


    def self.search_dietary_restrictions(restaurant, kw)
        Order.where("restaurant_id = ? AND dietary_restrictions LIKE ?", restaurant.id, "%#{kw}%" )
    end

    def self.search_flavor_preferences(restaurant, kw)
        Order.where("restaurant_id = ? AND flavor_preferences LIKE ?", restaurant.id, "%#{kw}%" )
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_restaurant, only: [:new, :create]
    before_action :set_order, only: [:show, :edit, :update, :destroy]
    before_action :user_has_permission?, only: [:edit, :update, :destroy]

    def new 
        @order = @restaurant.orders.build 
    end

    def create 
        @order = @restaurant.orders.build(order_params)
        @order.user = current_user
        if @order.save 
            redirect_to edit_order_path(@order), notice: "Order was successfully created."
        else 
            render :new 
        end
    end

    def show 
       
    end

    def index 
        if params[:restaurant_id]
            set_restaurant
            set_restaurant_orders
        else 
            @user= User.find(params[:user_id])
            @orders = @user.orders
        end
    end

    def edit 

    end

    def update 
       if @order.update(order_params)
            redirect_to order_path(@order), notice: "Order was successfully updated."
       else 
            render :edit 
       end
    end

    def destroy 
        restaurant = @order.restaurant 
        @order.destroy 
        redirect_to restaurant_path(restaurant), notice: "Order was successfully deleted."
    end

    private 
    def set_restaurant 
        @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def order_params 
        params.require(:order).permit(:name, :people, :dietary_restrictions, :flavor_preferences, :description, dish_orders_attributes: [:dish_id, :quantity, :special_requests, :id] )
    end

    def set_order 
        @order = Order.find(params[:id])
    end

    def user_has_permission? 
        unless current_user == @order.user 
            redirect_to order_path(@order), alert: "You do not have permission to perform this action."
        end
    end

    def set_restaurant_orders
        if params[:order_by] == "people"
            @orders = @restaurant.orders.sort_by_people
        elsif params[:order_by] == "created_at"
            @orders = @restaurant.orders.sort_by_created_at
        elsif params[:q_diet]
            @orders = Order.search_dietary_restrictions(@restaurant, params[:q_diet])
        elsif params[:q_flavor]
            @orders = Order.search_flavor_preferences(@restaurant, params[:q_flavor])
        else 
            @orders = @restaurant.orders
        end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper

    
end

app/views/orders/_form.html.erb
<%= form_with( model: [@restaurant, @order] , local: true) do |f| %>

    <% if @order.errors.any? %>
        <div id="error_explanation">
            <ul>
                <% @order.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %> <br>
    <%= f.label :people %>
    <%= f.number_field(:people, in: 1..50, step: 1) %> <br>
    <%= f.label :dietary_restrictions %>
    <%= f.text_field :dietary_restrictions %> <br>
    <%= f.label :flavor_preferences %>
    <%= f.text_field :flavor_preferences %> <br>
    <%= f.label :description %>
    <%= f.text_area :description %> <br>

    <h3>Dishes: </h3>
    <br>
    <%= f.fields_for :dish_orders do |dish_orders_form| %>
        <%= dish_orders_form.object.dish.translated_name %> 
        <%= dish_orders_form.hidden_field :dish_id, value: dish_orders_form.object.dish_id  %>
        <%= dish_orders_form.label :quantity %>
        <%= dish_orders_form.number_field(:quantity, in: 0..10, step: 1) %> <br>
        <%= dish_orders_form.label :special_requests %>
        <%= dish_orders_form.text_field :special_requests  %>
        <%= link_to  "Remove from Order", dish_order_path(dish_orders_form.object), method: "delete" %>        
        <br>
        <br>
    <% end %>
    <br>
    <%= f.submit class: "border-button" %>
<% end %>

app/views/orders/_index.html.erb
<h1>Orders: </h1>
<div class="orders-index">
<% orders.each do |order| %>
    <div class="order-item">
        <div class="order-info">
            <h4> <%= link_to  order.name, order_path(order) %> by <%= link_to order.user.name, user_path(order.user) %></h4>
            <p><%= order.created_at.strftime("%m/%d/%Y") %></p>
            <p> <%= order.dishes.count%> dishes for <%= order.people %> people</p>
            <p>Dietary Restrictions: <%=order.dietary_restrictions %> </p>
            <p>Flavor preferences: <%= order.flavor_preferences %> </p>
            <p>Description: <%= order.description %> </p>
        </div>
        <%= render  partial: "dishes/preview_index", locals: {dishes: order.dishes.first(3)} %>
        
        
    </div>
<% end %>
</div>

app/views/orders/_search.html.erb
<h3>Sort Orders By:</h3>
<%= form_with(url: restaurant_orders_path(@restaurant), method: "get", local: true) do %>
    <%= select_tag(:order_by, options_for_select([["Number of people", "people"], ["Date Posted", "created_at"]])) %>
    <%= submit_tag "Sort", class: "border-button" %>
<% end %>

<%= form_with(url: restaurant_orders_path(@restaurant), method: "get", local: true) do %>
<%= label_tag :q_diet, "Search by dietary restriction" %>
<%= text_field_tag (:q_diet) %>
<%= submit_tag "Search", class: "border-button" %>
<% end %>

<%= form_with(url: restaurant_orders_path(@restaurant), method: "get", local: true) do %>
<%= label_tag :q_flavor, "Search by flavor preference" %>
<%= text_field_tag (:q_flavor) %>
<%= submit_tag "Search", class: "border-button" %>
<% end %>

app/views/orders/edit.html.erb
<h1>Edit Your order</h1>

<%= render  "form" %>

app/views/orders/index.html.erb
<%= render  "restaurants/show" if @restaurant %>

<%= render  "users/show" if @user %>

<%= render  "search" if @restaurant %>

<%= render  partial: "index", locals: {orders: @orders } %>

app/views/orders/new.html.erb
<h1>New Order at: <span lang="zh"><%= @restaurant.chinese_name %></span> <%= link_to non_chinese_names(@restaurant), restaurant_path(@restaurant) %> </h1>

<%= render  "form" %>

app/views/orders/show.html.erb
<h1><%= @order.name %> at <span lang="zh"><%= @order.restaurant.chinese_name %></span> <%= link_to  non_chinese_names(@order.restaurant), restaurant_path(@order.restaurant) %></h1>
<p>by: <%= link_to  @order.user.name, user_path(@order.user) %></p>
<p>Number of people: <%= @order.people %></p>
<p>Dietary Restrictions: <%= @order.dietary_restrictions %></p>
<p>Flavor Preferences: <%= @order.flavor_preferences %></p>
<p>Description: <%= @order.description  %></p>
<% if user_has_permission?(@order) %>
    <nav class="order">
    <%= link_to  "Edit", edit_order_path(@order) %>
    <%= link_to  "Delete", order_path(@order), method: "delete", data: { confirm: 'Are you sure?' } %>
    <%= link_to  "Add more dishes", restaurant_dishes_path(@order.restaurant) %>
    </nav>
<% end %>

<%= render  partial: "dishes/index", locals: {dishes: @order.dishes } %>