config/routes.rb
Rails.application.routes.draw do
  
  
 
  resources :users, only: [:new, :create, :show] do 
    resources :translations, :orders, :restaurants, :comments, only: [:index]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#facebook'
  delete '/sessions', to: 'sessions#destroy'

  resources :restaurants do 
    resources :translations, only: [:new, :create, :index]
    resources :orders, only: [:new, :create, :index]
    resources :dishes, only: [:index]
  end

  resources :translations, only: [:show, :edit, :update, :destroy] do 
    resources :dishes, only: [:new, :create]
    resources :comments, only: [:new, :create, :index]
  end

  resources :orders, only: [:show, :edit, :update, :destroy]
  resources :dishes, only: [:show, :edit, :update, :destroy] do 
    resources :dish_orders, only: [:create]
  end
  resources :dish_orders, only: [:destroy]
  resources :comments, only: [:show, :edit, :update, :destroy]
   
  
  root 'application#home'

  get '/read', to: 'polly#read'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :translations 
    has_many :languages, through: :translations 
    has_many :dishes 
    has_and_belongs_to_many :cuisines 
    belongs_to :user 
    has_many :orders 
    has_one_attached :restaurant_image
    
    validates :chinese_name, :translated_name, :country, :province, :city, :district, :street, presence: true 
   

    

    def top_rated_translations(n) 
        sort_translations_by_rating.first(n)
    end

    def most_recent_orders(n)
        Order.where("restaurant_id = ?", self.id).order(created_at: :desc).first(n)
    end

    def sort_translations_by_rating
        self.translations.sort_by { |t| t.average_rating }.reverse
    end

    def sort_translations_by_dishes_count
        self.translations.sort_by { |t| t.dishes.size }.reverse
    end

    
   


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
    before_action :user_has_permission?, only: [:edit, :update, :destroy]
    skip_before_action :check_if_logged_in, only: [:show, :index]

    def index 
        set_restaurants
    end

    def new 
        @restaurant = Restaurant.new 
    end

    def create 
        @restaurant = current_user.restaurants.build(restaurant_params)
        if @restaurant.save
            redirect_to restaurant_path(@restaurant), notice: "Restaurant was successfully created."
        else 
            render :new 
        end
    end

    def show 
    end

    def edit 
    end

    def update 
        if @restaurant.update(restaurant_params)
            redirect_to restaurant_path(@restaurant), notice: "Restaurant was succesfully updated."
        else 
            render edit_restaurant_path(@restaurant)
        end
    end

    def destroy 
        if @restaurant.translations.length >= 1
            flash.alert= "Could not delete restaurant."
            render template: "restaurants/show"
        else 
            @restaurant.destroy
            redirect_to restaurants_path, notice: "Restaurant was successfully destroyed."
        end
    end

    private 

    def restaurant_params 
        params.require(:restaurant).permit(:chinese_name, :pinyin_name, :translated_name, :country, :province, :city, :district, :street, :restaurant_image, cuisine_ids: [])
    end

    def set_restaurant 
        @restaurant = Restaurant.find(params[:id])
    end

    def user_has_permission? 
        unless current_user == @restaurant.user 
            redirect_to restaurant_path(@restaurant), alert: "You do not have permission to perform this action."
        end
    end

    def set_restaurants 
        if params[:user_id]
            @user= User.find(params[:user_id])
            @restaurants = @user.restaurants 
        elsif params[:q_city]
            @restaurants = Restaurant.where("city = ?", params[:q_city])
        elsif params[:q_name]
            @restaurants = Restaurant.where("translated_name = ?", params[:q_name])
        elsif params[:q_cuisine]
            @restaurants = Cuisine.find(params[:q_cuisine][:id]).restaurants
        elsif params[:q_language]
            @restaurants = Language.restaurants_from_id(params[:q_language][:id])
        else 
            @restaurants = Restaurant.all         
        end
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

    def full_address(r)
        "#{r.country}, #{r.province}, #{r.city}, #{r.district},\n\n#{r.street}"
    end

    def restaurant_cuisines(r)
        r.cuisines.map { |c| c.english_name }.join(", ")  
    end

    
    
    
end

app/views/restaurants/_form.html.erb
        <%= cloudinary_js_config %>

<%= form_with model: @restaurant, local: true do |f| %>

<% if @restaurant.errors.any? %>
    <div id="error_explanation">
       <ul>
            <% @restaurant.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>

<% end %>

    <h3>Name:</h3>
    <%= f.label :chinese_name %>
    <%= f.text_field :chinese_name %><br>
    <%= f.label :pinyin_name %>
    <%= f.text_field :pinyin_name %> <br>
    <%= f.label :translated_name %>
    <%= f.text_field :translated_name %> <br>
    <h3>Cuisine</h3>
    <%=f.collection_check_boxes(:cuisine_ids, Cuisine.all, :id, :english_name) %>
    <h3>Address:</h3>
    <%= f.label :country %>
    <%= f.text_field :country %> <br>
    <%= f.label :province %>
    <%= f.text_field :province %> <br>
    <%= f.label :city %>
    <%= f.text_field :city %> <br>
    <%= f.label :district %>
    <%= f.text_field :district %> <br>
    <%= f.label :street %>
    <%= f.text_field :street %> <br>

    <br>
    <%= f.label :restaurant_image, "Add a picture of the restaurant front door/sign to help people find it"%> <br>
    <%= f.file_field :restaurant_image %>
    <br>
    <%= f.submit %>
<% end %>

app/views/restaurants/_search.html.erb
<div class="search">
<%= form_with(url: "/restaurants", method: "get", local: true, class: "one-line-form") do %>
    <%= text_field_tag(:q_city) %>
    <%= submit_tag "City", class: "border-button" %>
<% end %>

<%= form_with(url: "/restaurants", method: "get", local: true, class: "one-line-form") do %>
    <%= text_field_tag(:q_name) %>
    <%= submit_tag "Name", class: "border-button" %>
<% end %>

<%= form_with(url: "/restaurants", method: "get", local: true, class: "one-line-form") do %>
    
    <%= collection_select(:q_cuisine, :id, Cuisine.all, :id, :english_name) %>
    <%= submit_tag "Cuisine", class: "border-button" %>
<% end %>

<%= form_with(url: "/restaurants", method: "get", local: true, class: "one-line-form") do %>
    
    <%= collection_select(:q_language, :id, Language.all, :id, :name) %>
    <%= submit_tag "Language", class: "border-button" %>
<% end %>
</div>

app/views/restaurants/_show.html.erb
<audio id="player"></audio>
<div class="top-content">
    <div class="image-name">
        <%= cl_image_tag @restaurant.restaurant_image.key, width: 450, sign_url: true if @restaurant.restaurant_image.attached? %>
        
        <div class="name-overlay">
            <h1 lang="zh"><%= @restaurant.chinese_name %> </h1>
            <form id="input" method="GET" action="/read">
                <%= hidden_field_tag(:text, @restaurant.chinese_name) %>
                <input type="submit" value="Listen" id="submit" class="border-button" />
            </form>
            <h2 class="name"><%= non_chinese_names(@restaurant) %> </h2>
        </div>
    </div>

    <div class="description">
        <p>Address: <%= full_address(@restaurant) %> </p>

        <p>Cuisine: <%= restaurant_cuisines(@restaurant) %> </p>
        
        <p> Profile created by: 
            
                <%= link_to @restaurant.user.name, user_path(@restaurant.user) %>
            
            
        </p>
        <nav class="restaurant">
            <%= link_to  "Edit Restaurant Profile", edit_restaurant_path(@restaurant) if user_has_permission?(@restaurant) %>
            <%= link_to  "Delete", restaurant_path(@restaurant), method: "delete", data: { confirm: 'Are you sure?' } if user_has_permission?(@restaurant) %>
            <%= link_to  "Dishes", restaurant_dishes_path(@restaurant) %>
            <%= link_to  "Translations", restaurant_translations_path(@restaurant) %>
            <%= link_to  "Orders", restaurant_orders_path(@restaurant) %>
            <%= link_to  "Restaurant Profile", restaurant_path(@restaurant) %>
            <%= link_to  "Add Translation",  new_restaurant_translation_path(@restaurant) %>
            <%= link_to  "Add Order", new_restaurant_order_path(@restaurant) %>
        </nav>
    </div>
</div>
<script>
        // document.addEventListener("DOMContentLoaded", function () {
        //     var input = document.getElementById('input'),
        //         text = document.getElementById('text'),
        //         player = document.getElementById('player'),
        //         submit = document.getElementById('submit');
                
        //     input.addEventListener('submit', function (event) {
            
        //         player.src = '/read?text=' + encodeURIComponent(text.value);
        //         player.play();
            
        //         event.preventDefault();
        //     });
        // });
    </script>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant profile:</h1>

<%= render  "form" %>

app/views/restaurants/index.html.erb
<%= render  "users/show" if @user %>

    


<div class="restaurant-list">

    <div class="restaurant-index-options">
        <h1>Choose a Restaurant</h1>
        <%= render  "search" if !@user %>
        <%= link_to  "Or add a restaurant", new_restaurant_path %>
    </div>
    
    <% @restaurants.each do |r| %>
    <div class="index-content">  
        <%= cl_image_tag r.restaurant_image.key, width: 300 if r.restaurant_image.attached? %>
        <div class="index-description">            
            <h2 lang="zh"> <%= r.chinese_name%> </h2>
            
            <%= link_to  non_chinese_names(r), restaurant_path(r) %> 
            
            <br>
            <p><%= full_address(r) %></p>
            <p>Number of menu translations: <%= r.translations.count %> </p>
        </div>
    </div>
    <% end %>
</div>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant profile:</h1>

<%= render  "form" %>

app/views/restaurants/show.html.erb
<%= render  "show" %>

<%= render  partial: "translations/index", locals: {translations: @restaurant.top_rated_translations(3) } %>


<%= link_to  "View All Tranlations", restaurant_translations_path(@restaurant) %>


<%= render  partial: "orders/index", locals: {orders: @restaurant.most_recent_orders(3)} %>


<%= link_to  "View All Orders", restaurant_orders_path(@restaurant) %>